package io.github.xinyangpan.ella.core.bo;

public enum Status {
	// LIVE STATUS, PLACED COULD BE PARTIAL_FILLED
	PLACING, PLACED, CANCELLING,
	// FINAL STATUS
	PARTIAL_FILLED, FILLED, NONE_FILLED,
	CANCELLED, CANCEL_FAILED;
}